[build]
builder = "NIXPACKS"
buildCommand = "pip install Flask flask-cors requests"

[deploy]
startCommand = "python3 license_api_server.py"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[start]
cmd = "python3 license_api_server.py"
